pelican-dev/wings

server/server.go
Adds a function to parse start commands in wings directly.
Potential to remove the need in the entrypoint to support using `exec` vs `eval`
=> Parse start command in wings

environment/docker.go, router/router.go, router/router_system.go, system/system.go
/api/system/docker/disk endpoint provides disk utilization of the docker daemon.  Example output:
```
$ curl localhost:8080/api/system/docker/disk
{"containers_size": "163.4MB", "images_total":4,"images_active":2,"images_size":"181MB","build_cache_size":0}
```
=> Add Docker disk usage endpoint at /api/system/docker/disk

config/config.go, go.sum, router/router.go, router/router_server.go, server/server.go
Deletes all backups unless the wings config System.Backups.RemoveBackupsOnServerDelete is set to false.
Fixes pelican-dev/panel#145
=> Delete backups on server delete

cmd/root.go
The develop branch does not exists its main so the link is a 404
=> Update License link

go.mod, go.sum, server/server.go
Fix the variables in bash compare function been replaced and if their empty then the syntax is invalid.
This change is desinged by parker.
- with regex it check if a variable if is in between [[ ]] and if it is replace it with a placeholder. This is needed as Sometimes a variable is used in a compare function and outside of it. 
- then it does a find and replace off all variables what now the placeholder ofc does not match anymore
- then replace the placeholders back with their original ${} form
Go told me to run some command about a specifc package as it is directly used in a wings file. 
This was tested on the generic nodejs egg what was known for having issues.
=> Fix: Startup parsing

.github/workflows/push.yaml
Because we bumpt the go version to 1.21.9 and those 2 lines were not changed so there are no artifacts anymore to the actions attached
=> fix actions artifacts

cmd/root.go
A (temp) fix for Ubuntu that may have docker snap installed what does not work with the current wings release
- Temp start a docker client and get its DockerRootDir what on snap docker is specific to the snap dir
=> Detect snap docker

server/server.go
- Allow a server to set a time zone that is not the same as the one in that wings config
- This is done with the env variable `SERVER_TIMEZONE` 
- If it does not exist then it will use the time zone out of the wings config
- if it exists but is empty it will still use the wings config one
- if it exists it does a check with the time library if it is a valid timezone, if it is it sets it to the TZ variable if not it falls back to the wings config one
This maybe not that useful for now (for some it will), but if the panel add-ons feature is there you can just make a fancy UI for it
=> Allow to specify the server Timezone at egg level

server/backup/backup_s3.go
Fixes #26 by adding back mkdir for the temporary archive that gets stored locally before upload to S3
> Tested locally with Minio should work with S3/R2 as the issue is with the temp dir not being made and not the API itself
=> Fixes S3 backup error #26 

server/mounts.go
- validate if the source path exists on disk
- If the target includes /home/container then also do not mount it
=> Update mount validation

environment/docker/container.go
`proot` is a program known for its usage in creating unprivileged chroots.
This program essentially gives the user the capability create a chroot into another system without any permissions, effectively turning the container into a "server" - which is not an intended use for a container.
However, this program relies on a unprivileged system call in Linux systems known as `ptrace`, and by disabling it, scripts such as PteroVM or any of its derivatives will be rendered useless.
Before merging, please conduct some tests as this might cause potential break in some eggs (maybe?)
=> Dropping "sys_ptrace" capability.

config/config.go, server/mounts.go
Allow to bypass the check for not allowing mount in /home/container
closes #41
=> allow to bypass /home/container mount check

router/router_download.go, router/router_server_files.go, server/filesystem/compress.go, sftp/handler.go
- Files within the file_denylist can not be removed anymore
- Files within that list can not be created anymore:
- If the file is put their by for example the egg install script then the user can not see what is in it
- This includes also over SFTP
- Application (tested by exec in the container) can still read the files just fine
=> Enforce the egg's file denylist more thoroughly

cmd/configure.go
`remote` won't be parsed from the json due to [pterodactyl/wings@5415f8a](https://github.com/pterodactyl/wings/commit/5415f8ae07f533623bd8169836dd7e0b933964de#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17R309)
Needed for https://github.com/pelican-dev/panel/pull/627
=> Fix Auto Deploy remote

environment/docker/power.go
- Add an extra debug print that can be very usefull
- make `^C` send SIGINT and not SIGTERM 
- use ContainerKill and not ContainerStop as stop will stop printing the console output (shutdown logs for a game for example)
=> Stoplogic fix for default signal and shutdown console printing

server/config_parser.go
- This PR should allow having a variable in the filepath in the configuration parser
- closes https://github.com/pelican-dev/panel/discussions/505
This works:
=> Allow for variables in the configuration parser filename

cmd/root.go, config/config.go, router/router.go, router/router_server_files.go, router/router_server_files_search.go, server/filesystem/filesystem.go, server/filesystem/stat.go
This PR ads an endpoint that allows you to search through files./
Closed #43 
You give it a directory and a pattern to search, and it will return with a list of files (recursively) that matched that pattern.
Valid patterns:
- txt
- .txt
- *.txt
- start (if file for example is StartServer.bat)
- server.jar (full filename)
a pattern must be at least 3 char long
all patterns are treaded case-insensitive
What it will return:
where name is the relative path + the filename
- BlacklistedDirs: **currently does work because of some panic error** but for now hard-coded to:
var blacklist = []string{"node_modules", ".wine", "appcache", "depotcache", "vendor"}
Are the current blacklisted dir where we will not go in recursive
- MaxRecursionDepth: this works and is the max of how deep the recursion will …
=> add File search endpoint

router/middleware/request_error.go, router/router_server_files.go
Makes the middleware not error out if a file does not exist and make wings return 404 as for some reason the asFilesystemError function code seems to be ignored
#48
=> Fix file err NotExist returning 500 instead of 404

environment/docker/power.go
Enhance container stop logic to handle non-responsive containers more reliably.
Previously, we relied on `ContainerKill` to stop a Docker container with the signal provided. If the operation returned without an error, we assumed the container had stopped. However, according to the [Docker Kill Documentation](https://docs.docker.com/reference/cli/docker/container/kill/#description), if the provided signal is not appropriate for the application, the container may continue running while our system incorrectly assumes it has stopped. This leads to errors on the next start attempt because the container is still active.
Initially, we attempted to use `ContainerStop`, which sends the signal and escalates to `SIGKILL` if the container does not stop within a specified timeout. However, this …
=> Ensure Accurate Container Stop State with Signal Validation

parser/parser.go, server/config_parser.go
* This should add the possibility to disable automatic creation of the configuration files by the daemon
* Closes https://github.com/pelican-dev/panel/discussions/608#discussion-7275965 (as explained in the discussion, adding a flag instead of glob support might be better)
In very specific cases, configuration files should not be created by the daemon before the server first startup as they have not been created during the installation process.
This new flag enables egg creators to specify (default true) if the file should be created or not when the daemon tries to parse it.
(This is just an example on the Vanilla Minecraft egg, this is not where I think the flag would be useful)
When the daemon tries to open the file to parse it, changing the function to Open instead of Touch makes it …
=> Add a parameter to disable configuration file automatic creation

.github/workflows/push.yaml, cmd/root.go, cmd/selfupdate.go
With `wings update` wings can self fetch the latest release, download it, check the sha256 sum, replace itself and then and then restart.
=> add selfupdate

server/install.go
- List the kernel version of the wings that ran the egg install script, as it can be useful because some games are known to not work on some kernels
=> feat: Add kernel version to egg installation logs

config/config.go, server/activity.go, server/crash.go
- Log in the activity that a server has crashed with its exit code, oomkilled, and the last 2 console lines
Note: needs a panel change for this to be visible
=> Activity log crash

docker-compose.example.yml
With docker version 25.05 the `version` in docker-compose.yml is obsolete
=> Remove outdated `version` in compose file

router/router_server_files.go, server/filesystem/filesystem.go
Catch and inform the panel about
https://github.com/pelican-dev/panel/pull/1135
=> Fail when trying to edit a `Directory` like if it was `File` content

cmd/selfupdate.go
**Description:**  
This change replaces `os.Rename` with `io.Copy` to properly update the executable while preserving permissions and ensuring compatibility across filesystems.
**Changes:**  
- Replaced `os.Rename` with `io.Copy` for safer overwriting.  
- Captures and restores the executable’s permissions.  
**Why this change?**  
`os.Rename` caused issues with permissions and filesystem compatibility. This fix ensures reliable, permission-preserving updates.
**Impact:**  
- Fixes permission and filesystem compatibility issues.
=>  Replace os.Rename with io.Copy for cross filesystem transfers

server/filesystem/compress.go, server/filesystem/filesystem.go
https://github.com/pelican-dev/wings/pull/83 got merged too soon, if you create an archive with a name that already exists it overwrites it instead of appending `copy` to its name
> I know `findCopySuffix` is also used in `copyFile` but i didn't feel like checking the same thing that's already in the loop so i though might as well adapt it to not add suffix if the file doesn't already exist.
=> Use `findCopySuffix`

config/config.go, router/router_server_files_search.go
Needs testing, but I hope it helps.
I also had to edit the `isBlacklisted` function to avoid edge cases (like `.github` folders).
I haven't worked that much with Golang, so I hope my understanding of the `isBlacklisted` was correct
=> feat (Search): Ignore .git folder
